# Generated by Django 5.2.6 on 2025-10-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='aadhaar_hash',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='masked_aadhaar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
