# Generated by Django 5.2.6 on 2025-10-14 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_aadhaar_hash_patient_masked_aadhaar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfile',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='patients.patient'),
        ),
    ]
