# Generated by Django 5.2.6 on 2025-10-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_recordgroup_patientfile_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientfile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.recordgroup'),
        ),
        migrations.AlterField(
            model_name='patientfile',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='patientfile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recordgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
