# Generated by Django 5.2.6 on 2025-10-14 16:44

import django.db.models.deletion
import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patientfile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfile',
            name='file',
            field=models.FileField(upload_to=patients.models.patient_file_upload_to),
        ),
        migrations.AlterField(
            model_name='patientfile',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='patients.patient'),
        ),
    ]
