# Generated by Django 5.2.6 on 2025-10-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patientfile_file_alter_patientfile_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfile',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientfile',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
